[package]
name = "ferrischat_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "ferrischat_db",
  "ferrischat_webserver",
  "ferrischat_macros",
  "ferrischat_redis",
]

[dependencies]
ferrischat_webserver = { path = "ferrischat_webserver", version = "0.1.0" }
actix-web = "3"
env_logger = "0.9"
time = "*"