on:
  pull_request:

  push:
    branches:
      - master


name: Linters

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:latest"
        env:
          POSTGRES_PASSWORD: "postgres"
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
          
      - uses: Swatinem/rust-cache@v1

      - name: "install sqlx cli"
        run: "cargo install sqlx-cli"

      - name: "run database migrations"
        run: "cargo sqlx database setup"
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/ferris_chat"

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D clippy::pedantic -D clippy::nursery -A clippy::too_many_lines
          name: Clippy Output
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/ferris_chat"
